django-201/django-201/profiles/urls.py
from django.urls import path
from .views import EditProfileView, ProfileDetailView, FollowView


app_name = "profiles"

urlpatterns = [
    path('edit/', EditProfileView.as_view(), name='edit_profile'),
    path("<str:username>/", ProfileDetailView.as_view(), name="detail"),
    path("<str:username>/follow/", FollowView.as_view(), name="follow"),
]

django-201/django-201/til/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include
from feed import urls as feed_urls
from profiles import urls as profiles_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(feed_urls, namespace="feed")),
    path("profile/", include(profiles_urls, namespace="profiles")),
    path("accounts/", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django-201/django-201/profiles/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from sorl.thumbnail import ImageField

class Post(models.Model):
    text = models.CharField(max_length=100, blank=False, null=False)
    image = ImageField()
    
    def __str__(self):
        return self.text

class Profile(models.Model):
    id = models.BigAutoField(primary_key=True)
    image = ImageField(upload_to='profiles', blank=True, null=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    username = models.CharField(max_length=150, unique=True, default="")
    bio = models.TextField(blank=True)

    def __str__(self):
        return self.username

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    """Create a new Profile() object when a Django User is created."""
    if created:
        username = instance.email.split('@')[0]  # Extract username from email
        counter = 1
        # Check if the generated username already exists
        while Profile.objects.filter(username=username).exists():
            username = instance.email.split('@')[0] + str(counter)
            counter += 1
        Profile.objects.create(user=instance, username=username)
    else:  # If the user already exists, ensure the username is unique
        if not instance.profile.username:
            username = instance.email.split('@')[0]  # Extract username from email
            counter = 1
            # Generate unique username if needed
            while Profile.objects.filter(username=username).exists():
                username = instance.email.split('@')[0] + str(counter)
                counter += 1
            instance.profile.username = username
            instance.profile.save()

django-201/django-201/profiles/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile  
        fields = ['username', 'bio', 'image']
        
    def __init__(self, *args, **kwargs):
        super(ProfileEditForm, self).__init__(*args, **kwargs)
        self.fields['username'].initial = self.instance.user.username
        
    def save(self, commit=True):
        profile = super(ProfileEditForm, self).save(commit=False)
        new_username = self.cleaned_data.get('username')
        new_bio = self.cleaned_data.get('bio')
        new_image = self.cleaned_data.get('image')
        

        
        if new_username and new_username != profile.user.username:
            profile.user.username = new_username
            profile.user.save() 
        # Update profile bio
        profile.bio = new_bio

        # Update profile image
        if new_image:
            profile.image = new_image

        # Save changes
        if commit:
            profile.save()
        return profile
      

django-201/django-201/profiles/views.py
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView, View
from django.views.generic.edit import UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, HttpResponseBadRequest
from feed.models import Post
from followers.models import Follower
from .models import Profile
from .forms import ProfileEditForm
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib import messages
from django.urls import reverse

def edit_profile(request):
    user = request.user
    profile = user.profile  

    if request.method == 'POST':
        form = ProfileEditForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('profiles:edit_profile')
    else:
        form = ProfileEditForm(instance=profile)

    context = {'form': form}
    return render(request, 'edit_profile.html', context)



class EditProfileView(LoginRequiredMixin, UpdateView):
    model = Profile
    form_class = ProfileEditForm
    template_name = 'profiles/edit_profile.html'
    success_url = '/'
    
    def get_success_url(self):
        return reverse('profiles:detail', kwargs={'username': self.request.user.username})
    
    
    def get_object(self, queryset=None):
        return self.request.user.profile

    def form_valid(self, form):
        form.save()
        messages.success(self.request, 'Profile updated successfully.')
        return super().form_valid(form)
       
class ProfileDetailView(DetailView):
    http_method_names = ["get"]
    template_name = "profiles/detail.html"
    model = User
    context_object_name = "user"
    slug_field = "username"
    slug_url_kwarg = "username"

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        user = self.get_object()
        context = super().get_context_data(**kwargs)
        profile = user.profile
        context['profile'] = profile
        context['total_posts'] = Post.objects.filter(author=user).count()
        context['total_followers'] = Follower.objects.filter(following=user).count()
        if self.request.user.is_authenticated:
            context['you_follow'] = Follower.objects.filter(following=user, followed_by=self.request.user).exists()
        messages.info(self.request, '')
        
        return context


class FollowView(LoginRequiredMixin, View):
    http_method_names = ["post"]

    def post(self, request, *args, **kwargs):
        data = request.POST.dict()

        if "action" not in data or "username" not in data:
            return HttpResponseBadRequest("Missing data")

        try:
            other_user = User.objects.get(username=data['username'])
        except User.DoesNotExist:
            return HttpResponseBadRequest("Missing user")

        if data['action'] == "follow":
            # Follow
            follower, created = Follower.objects.get_or_create(
                followed_by=request.user,
                following=other_user
            )
        else:
            # Unfollow
            try:
                follower = Follower.objects.get(
                    followed_by=request.user,
                    following=other_user,
                )
            except Follower.DoesNotExist:
                follower = None

            if follower:
                follower.delete()

        return JsonResponse({
            'success': True,
            'wording': "Unfollow" if data['action'] == "follow" else "Follow"
        })

django-201/django-201/profiles/templates/profiles/detail.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}{{ user.username }}{% endblock title %}

{% block body %}
<div class="rounded rounded-t-lg overflow-hidden shadow max-w-xs my-3">
  	<img src="https://i.imgur.com/dYcYQ7E.png" class="w-full" />
    <div class="flex justify-center -mt-8">
        {% thumbnail user.profile.image "100x100" crop="center" as im %}
            <img src="{{ im.url }}" class="rounded-full border-solid border-white border-2 -mt-3">
        {% endthumbnail %}
    </div>
	<div class="text-center px-3 pb-6 pt-2">
        <h3 class="text-black text-sm bold font-sans">{{ user.username }}</h3>
        <p>{{ profile.bio }}</p> <!-- Display user bio here -->
        <!-- Messages loop should end here -->
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                <p>{{ profile.bio }}<p>
            </div>
        {% endfor %}
        <!-- Messages loop ends here -->
        {% if request.user.is_authenticated %}
            {% if request.user != user %}
                <div class="mt-3">
                    <button class="bg-white text-gray-800 font-bold rounded border-b-2 border-green-500 hover:border-green-600 hover:bg-green-500 hover:text-white shadow-md py-1 px-3 text-xs inline-flex items-center js-follow" data-username="{{ user.username }}" data-action="{% if you_follow %}un{% endif %}follow" data-url="{% url 'profiles:follow' user.username %}" type="button">
                        <span class="mr-2 js-follow-text">
                            {% if you_follow %}
                                Unfollow
                            {% else %}
                                Follow
                            {% endif %}
                        </span>
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                            <path fill="currentcolor" d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"></path>
                        </svg>
                    </button>
                </div>
            {% endif %}
        {% else %}
            <div class="mt-3 text-sm">Login to follow this user</div>
        {% endif %}
    </div>
  	<div class="flex justify-center pb-3 text-grey-dark">
      <div class="text-center mr-3 border-r pr-3">
        <h2>{{ total_posts }}</h2>
        <span>Posts</span>
      </div>
      <div class="text-center">
        <h2>{{ total_followers}}</h2>
        <span>Followers</span>
      </div>
  	</div>
</div>
{% endblock body %}

django-201/django-201/profiles/templates/profiles/edit_profile.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}edit_profile{% endblock title %}

{% block body %}
<form class="w-full min-h-screen py-1 md:w-2/3 lg:w-3/4" method="post" action="{% url 'profiles:edit_profile' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="p-2 md:p-4">
        <div class="w-full px-6 pb-8 mt-8 sm:max-w-xl sm:rounded-lg">
            <h2 class="pl-6 text-2xl font-bold sm:text-xl">Public Profile</h2>

            <div class="grid max-w-2xl mx-auto mt-8">
                <div class="flex flex-col items-center space-y-5 sm:flex-row sm:space-y-0">
                    {% thumbnail user.profile.image "100x100" crop="center" as im %}
                    <img class="object-cover w-40 h-40 p-1 rounded-full ring-2 ring-indigo-300 dark:ring-indigo-500"
                        src="{{ im.url }}"
                        alt="Bordered avatar">
                    {% endthumbnail %}

                    <div class="flex flex-col space-y-5 sm:ml-8">
                        <label for="profile-picture" class="py-3.5 px-7 text-base font-medium text-indigo-100 focus:outline-none bg-[#202142] rounded-lg border border-indigo-200 hover:bg-indigo-900 focus:z-10 focus:ring-4 focus:ring-indigo-200 cursor-pointer">
                            Change picture
                        </label>
                        <input type="file" id="profile-picture" name="image" class="hidden">
                        
                    </div>
                </div>

                <div class="items-center mt-8 sm:mt-14 text-[#202142]">

                    <div
                        class="flex flex-col items-center w-full mb-2 space-x-0 space-y-2 sm:flex-row sm:space-x-4 sm:space-y-0 sm:mb-6">
                        <div class="w-full">
                            <label for="username"                               class="block mb-2 text-sm font-medium text-indigo-900 dark:text-white">Username</label>
                            <input type="text" id="username" name="username"
                                class="bg-indigo-50 border border-indigo-300 text-indigo-900 text-sm rounded-lg focus:ring-indigo-500 focus:border-indigo-500 block w-full p-2.5 "
                                placeholder="username" value="{{ user.username }}" required>
                        </div>

                    </div>
                
                    <div class="mb-6">
                        <label for="message"
                            class="block mb-2 text-sm font-medium text-indigo-900 dark:text-white">Bio</label>
                        <textarea id="message" rows="4" name="bio"
                            class="block p-2.5 w-full text-sm text-indigo-900 bg-indigo-50 rounded-lg border border-indigo-300 focus:ring-indigo-500 focus:border-indigo-500 "
                            placeholder="Write your bio here...">{{ user.profile.bio }}</textarea>
                    </div>

                    <div class="flex justify-end">
                        <button type="submit"
                            class="text-white bg-indigo-700  hover:bg-indigo-800 focus:ring-4 focus:outline-none focus:ring-indigo-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-indigo-600 dark:hover:bg-indigo-700 dark:focus:ring-indigo-800">Save</button>
                    </div>

                </div>
            </div>
        </div>
    </div>
</form>

{% endblock body %}